### PR TITLE
Patch for zig version 13

### PR DESCRIPTION
**Pull request by RohanVashisht1234**
There were no changes done to main.zig because it is working in zig 13 as well.
The build.zig file has been modified to support the latest format.
the build.zig.zon has been added as of the latest format.
rmsnorm.zig has been updated to adapt to the latest var and const forced correction.

### CODE REVIEW

**Comment by cgbur** [comment]
Hi sorry for the delay. Curious, do projects in v13 require a `zig.zon`? I don't really intend for others to be depending on this project as its not actively maintained.

**Comment by RohanVashisht1234** [comment]
See, the build.zig.zon is just for mentioning simple details about the project, a Zig project generally has a build.zig.zon, obviously it is not that necessary, but whenever we run zig init, it creates a build.zig.zon file in it. Just treat it like a manifest file for build.zig.

**Comment by RohanVashisht1234** [comment]
So, Any suggestions regarding build.zig.zon?

**Comment by cgbur** [comment]
I still need to check why the CI test is failing.

I am in favor of removing the zon file, I dont think its adds anything to the project. I would appreciate keeping some of the basic high level comments in the build script. The build scripts are a bit arcane and repo is mostly for education. Apologies for the delays this repo is not top of mind these days.

**Comment by RohanVashisht1234** [comment]
ok, no problem, I'll revert those changes and you can merge them.

**Comment by RohanVashisht1234** [comment]
Yes, done. The comments are now from the latest build.zig (v0.13.0).

**Comment by cgbur** [comment]
Any ideas why the test case is failing? Do you know if this was failing prior as well? I need to check on it or merge it anyways.

**Pull request closed without merging**
